Repository MEGWARE-HPC/xbat, pull requests merged in 2025-07, with the labels that each got.

#84 GraphExport update
  CHANGELOG.md
  src/ui/components/graphs/GraphExport.vue
  src/ui/components/graphs/GraphWrapper.vue
Labels: bug

#100 fixed missing group/metric and trace identifier in CSV output (#98)
  CHANGELOG.md
  src/backend/restapi/api/measurements.py
Labels: bug, enhancement

#24 Customize a syntax highlighting for CSV language in Editor
  CHANGELOG.md
  src/ui/assets/css/rainbow-colors.scss
  src/ui/components/Editor.client.vue
  src/ui/components/graphs/GraphExport.vue
  src/ui/utils/colors.ts
Labels: enhancement

#91 Endpoint for energy consumption
  CHANGELOG.md
  src/backend/restapi/api/measurements.py
  src/backend/restapi/api/openapi.yml
Labels: enhancement

#34 DocsNavigation loop and some updates about docs
  CHANGELOG.md
  README.md
  docs/components/DocsNavigation.vue
  docs/components/content/ActionButton.vue
  docs/content/docs/01.user/01.introduction.md
  docs/content/docs/01.user/02.get-started/job-configuration.md
  docs/content/docs/01.user/02.get-started/job-submission.md
  docs/content/docs/01.user/03.metrics/01.monitoring.md
  docs/content/docs/01.user/03.metrics/02.cpu.md
  docs/content/docs/01.user/03.metrics/04.memory.md
  docs/content/docs/01.user/ci.md
  docs/content/docs/01.user/likwid.md
  docs/content/docs/02.admin/01.setup/01.installation.md
  docs/content/docs/02.admin/01.setup/02.database.md
  docs/content/docs/02.admin/01.setup/03.slurm.md
  docs/content/docs/02.admin/01.setup/05.https.md
  docs/content/docs/02.admin/02.maintenance.md
  docs/content/docs/03.developer/02.architecture.md
  docs/content/docs/03.developer/03.setup.md
  docs/content/docs/03.developer/05.frontend.md
  docs/content/docs/03.developer/06.backend.md
  docs/content/docs/about.md
  docs/content/docs/demo.md
  src/ui/app.vue
Labels: enhancement
