Repository MEGWARE-HPC/xbat, pull requests merged in 2025-06, with the labels that each got.

#27 Fix theme and fonts issues in editor
  CHANGELOG.md
  src/ui/assets/css/editor-themes.scss
  src/ui/components/Editor.client.vue
Labels: bug

#33 Extend measurements CSV endpoint
  CHANGELOG.md
  src/backend/restapi/api/measurements.py
  src/backend/restapi/api/openapi.yml
Labels: enhancement

#79 Optimize frontend build and default to npm over bun
  CHANGELOG.md
  docker/ui.dockerfile
  docs/bun.lockb
  docs/content/docs/03.developer/03.setup.md
  docs/content/docs/03.developer/05.frontend.md
  docs/package-lock.json
  src/ui/bun.lockb
  src/ui/package-lock.json
Labels: chore
